### ISSUE TITLE
Failing unit test regarding signing  (simulator)

### ISSUE THREAD

**Issue by gustinmi** [status-im/status-keycard#90]
There are 4 unit test failing with gradlew test. JCardSim is selected as card provider. Is this because of simulator?
All files are default (wallet.json), no changes to code was made. Using java 1.8.LATEST.

im.status.keycard.KeycardTest > signTest() FAILED
org.opentest4j.AssertionFailedError: expected: <36864> but was: <28416>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:154)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:149)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:305)
at im.status.keycard.KeycardTest.verifySignResp(KeycardTest.java:1200)
at im.status.keycard.KeycardTest.signTest(KeycardTest.java:1153)

im.status.keycard.KeycardTest > exportKey() FAILED
org.opentest4j.AssertionFailedError: expected: <36864> but was: <28416>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:154)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:149)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:305)
at im.status.keycard.KeycardTest.exportKey(KeycardTest.java:1375)

im.status.keycard.KeycardTest > setPinlessPathTest() FAILED
org.opentest4j.AssertionFailedError: expected: <36864> but was: <28416>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:154)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:149)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:305)
at im.status.keycard.KeycardTest.setPinlessPathTest(KeycardTest.java:1280)

im.status.keycard.KeycardTest > deriveKeyTest() FAILED
org.opentest4j.AssertionFailedError: expected: <36864> but was: <28416>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:154)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:149)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:305)
at im.status.keycard.KeycardTest.verifyKeyDerivation(KeycardTest.java:1753)
at im.status.keycard.KeycardTest.deriveKeyTest(KeycardTest.java:1075)

**Comment by bitgamma** [comment]
simulator support has been fixed in the meantime
